### ISSUE TITLE
size() function broken.

### ISSUE THREAD

**Issue by cameronnapoli** [jeffThompson/PixelSorting#1]
From the processing reference documents:

> The size() function can only be used once inside a sketch, and it cannot be used for resizing.

![screen shot 2018-11-09 at 3 03 22 pm copy](https://user-images.githubusercontent.com/4724150/48292888-2f20a880-e431-11e8-844b-8937937f4c3a.png)

Error occurred on OS X El Capitan 10.11.6, Processing v3.4.

**Comment by jeffThompson** [comment]
Yeah, I'm afraid the Processing core changed a number of years ago and `size()` no longer directly supports variables. Since this project is quite old at this point, I'm not going to be able to change it to keep up with new versions of Processing.

You can hard-code the image size you're feeding in, or modify it to use the `settings()` function: https://processing.org/reference/settings_.html
